version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - .env
     
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homi
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
